package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihProyecto generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_PROYECTO", uniqueConstraints = @UniqueConstraint(columnNames = "NOMBRE"))
public class TMihProyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7193650183759001682L;
	private int codigo;
	private String nombre;
	private String descripcion;
	private Character estado;
	private Date feregistro;
	private Set<TMihLineanegocio> TMihLineanegocios = new HashSet<TMihLineanegocio>(0);
	private static final Log log = LogFactory.getLog(TMihProyecto.class);

	public TMihProyecto() {
	}

	public TMihProyecto(int codigo) {
		this.codigo = codigo;
	}

	public TMihProyecto(int codigo, String nombre, String descripcion,
			Character estado, Date feregistro, Set<TMihLineanegocio> TMihLineanegocios) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.feregistro = feregistro;
		this.TMihLineanegocios = TMihLineanegocios;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_proy_id")
	@SequenceGenerator(name="seq_proy_id", sequenceName="SEQ_MIH_PROYECTO",schema="SEMIH",allocationSize=5)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "NOMBRE", unique = true, length = 160)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 1600)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEREGISTRO", length = 7)
	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMihProyecto")
	public Set<TMihLineanegocio> getTMihLineanegocios() {
		return this.TMihLineanegocios;
	}

	public void setTMihLineanegocios(Set<TMihLineanegocio> TMihLineanegocios) {
		this.TMihLineanegocios = TMihLineanegocios;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombre();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
