package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TMihLogsId generated by hbm2java
 */
@Embeddable
public class TMihLogsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3647137560983489790L;
	private String tabla;
	private String usuario;
	private Character accion;
	private String descripcion;
	private Timestamp feregistro;

	public TMihLogsId() {
	}

	public TMihLogsId(String tabla, String usuario, Character accion,
			String descripcion, Timestamp feregistro) {
		this.tabla = tabla;
		this.usuario = usuario;
		this.accion = accion;
		this.descripcion = descripcion;
		this.feregistro = feregistro;
	}

	@Column(name = "TABLA", length = 120)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "USUARIO", length = 80)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ACCION", length = 1)
	public Character getAccion() {
		return this.accion;
	}

	public void setAccion(Character accion) {
		this.accion = accion;
	}

	@Column(name = "DESCRIPCION", length = 1600)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "FEREGISTRO", columnDefinition="timestamp with time zone")
	public Timestamp getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Timestamp feregistro) {
		this.feregistro = feregistro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMihLogsId))
			return false;
		TMihLogsId castOther = (TMihLogsId) other;

		return ((this.getTabla() == castOther.getTabla()) || (this.getTabla() != null
				&& castOther.getTabla() != null && this.getTabla().equals(
				castOther.getTabla())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getAccion() == castOther.getAccion()) || (this
						.getAccion() != null && castOther.getAccion() != null && this
						.getAccion().equals(castOther.getAccion())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getFeregistro() == castOther.getFeregistro()) || (this
						.getFeregistro() != null
						&& castOther.getFeregistro() != null && this
						.getFeregistro().equals(castOther.getFeregistro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTabla() == null ? 0 : this.getTabla().hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result
				+ (getAccion() == null ? 0 : this.getAccion().hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37
				* result
				+ (getFeregistro() == null ? 0 : this.getFeregistro()
						.hashCode());
		return result;
	}

}
