package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihCatalogoId generated by hbm2java
 */
@Embeddable
public class TMihCatalogoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3382238422716039921L;
	private short codmaestro;
	private String codigo;
	private static final Log log = LogFactory.getLog(TMihCatalogoId.class);

	public TMihCatalogoId() {
	}

	public TMihCatalogoId(short codmaestro, String codigo) {
		this.codmaestro = codmaestro;
		this.codigo = codigo;
	}

	@Column(name = "CODMAESTRO", nullable = false, precision = 4, scale = 0)
	public short getCodmaestro() {
		return this.codmaestro;
	}

	public void setCodmaestro(short codmaestro) {
		this.codmaestro = codmaestro;
	}

	@Column(name = "CODIGO", nullable = false, length = 120)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMihCatalogoId))
			return false;
		TMihCatalogoId castOther = (TMihCatalogoId) other;

		return (this.getCodmaestro() == castOther.getCodmaestro())
				&& ((this.getCodigo() == castOther.getCodigo()) || (this
						.getCodigo() != null && castOther.getCodigo() != null && this
						.getCodigo().equals(castOther.getCodigo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodmaestro();
		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getCodigo();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
