package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihParametro generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_PARAMETRO")
public class TMihParametro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6839147858568355791L;
	private String codigo;
	private String valor;
	private String descripcion;
	private Character espss;
	private static final Log log = LogFactory.getLog(TMihParametro.class);
	
	public TMihParametro() {
	}

	public TMihParametro(String codigo) {
		this.codigo = codigo;
	}

	public TMihParametro(String codigo, String valor, String descripcion) {
		this.codigo = codigo;
		this.valor = valor;
		this.descripcion = descripcion;
	}

	public TMihParametro(String codigo, String valor, String descripcion, Character espss) {
		this.codigo = codigo;
		this.valor = valor;
		this.descripcion = descripcion;
		this.espss = espss;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, length = 30)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "VALOR", length = 400)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "DESCRIPCION", length = 4000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESPSS", length = 1)
	public Character getEspss() {
		return espss;
	}

	public void setEspss(Character espss) {
		this.espss = espss;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getDescripcion();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
