package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihCatalogo generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_CATALOGO")
public class TMihCatalogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7112712872055164492L;
	private TMihCatalogoId id;
	private TMihTipocatalogo TMihTipocatalogo;
	private String descripcion;
	private Date feregistro;
	private static final Log log = LogFactory.getLog(TMihCatalogo.class);
	
	public TMihCatalogo() {
	}

	public TMihCatalogo(TMihCatalogoId id, TMihTipocatalogo TMihTipocatalogo) {
		this.id = id;
		this.TMihTipocatalogo = TMihTipocatalogo;
	}

	public TMihCatalogo(TMihCatalogoId id, TMihTipocatalogo TMihTipocatalogo,
			String descripcion, Date feregistro) {
		this.id = id;
		this.TMihTipocatalogo = TMihTipocatalogo;
		this.descripcion = descripcion;
		this.feregistro = feregistro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codmaestro", column = @Column(name = "CODMAESTRO", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "codigo", column = @Column(name = "CODIGO", nullable = false, length = 120)) })
	public TMihCatalogoId getId() {
		return this.id;
	}

	public void setId(TMihCatalogoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODMAESTRO", nullable = false, insertable = false, updatable = false)
	public TMihTipocatalogo getTMihTipocatalogo() {
		return this.TMihTipocatalogo;
	}

	public void setTMihTipocatalogo(TMihTipocatalogo TMihTipocatalogo) {
		this.TMihTipocatalogo = TMihTipocatalogo;
	}

	@Column(name = "DESCRIPCION", length = 400)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEREGISTRO", length = 7)
	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getDescripcion();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
}
