package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihRol generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_ROL")
public class TMihRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2220972524814216099L;
	private int codigo;
	private Character admusuario;
	private Character parametros;
	private Character entidades;
	private Character carga;
	private Character consultapuntual;
	private Character consultamasiva;
	private Character auditoria;
	private Character depuracion;
	private Character autorizar;
	private Date feregistro;
	private String nombre;
	private Set<TMihUsuario> TMihUsuarios = new HashSet<TMihUsuario>(0);
	private static final Log log = LogFactory.getLog(TMihRol.class);

	public TMihRol() {
	}

	public TMihRol(int codigo) {
		this.codigo = codigo;
	}

	public TMihRol(int codigo, Character admusuario, Character parametros,
			Character entidades, Character carga, Character consultapuntual,
			Character consultamasiva, Character auditoria,
			Character depuracion, Date feregistro, String nombre,
			Set<TMihUsuario> TMihUsuarios) {
		this.codigo = codigo;
		this.admusuario = admusuario;
		this.parametros = parametros;
		this.entidades = entidades;
		this.carga = carga;
		this.consultapuntual = consultapuntual;
		this.consultamasiva = consultamasiva;
		this.auditoria = auditoria;
		this.depuracion = depuracion;
		this.feregistro = feregistro;
		this.nombre = nombre;
		this.TMihUsuarios = TMihUsuarios;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "ADMUSUARIO", length = 1)
	public Character getAdmusuario() {
		return this.admusuario;
	}

	public void setAdmusuario(Character admusuario) {
		this.admusuario = admusuario;
	}

	@Column(name = "PARAMETROS", length = 1)
	public Character getParametros() {
		return this.parametros;
	}

	public void setParametros(Character parametros) {
		this.parametros = parametros;
	}

	@Column(name = "ENTIDADES", length = 1)
	public Character getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Character entidades) {
		this.entidades = entidades;
	}

	@Column(name = "CARGA", length = 1)
	public Character getCarga() {
		return this.carga;
	}

	public void setCarga(Character carga) {
		this.carga = carga;
	}

	@Column(name = "CONSULTAPUNTUAL", length = 1)
	public Character getConsultapuntual() {
		return this.consultapuntual;
	}

	public void setConsultapuntual(Character consultapuntual) {
		this.consultapuntual = consultapuntual;
	}

	@Column(name = "CONSULTAMASIVA", length = 1)
	public Character getConsultamasiva() {
		return this.consultamasiva;
	}

	public void setConsultamasiva(Character consultamasiva) {
		this.consultamasiva = consultamasiva;
	}

	@Column(name = "AUDITORIA", length = 1)
	public Character getAuditoria() {
		return this.auditoria;
	}

	public void setAuditoria(Character auditoria) {
		this.auditoria = auditoria;
	}

	@Column(name = "DEPURACION", length = 1)
	public Character getDepuracion() {
		return this.depuracion;
	}

	public void setDepuracion(Character depuracion) {
		this.depuracion = depuracion;
	}

	@Column(name = "AUTORIZAR", length = 1)
	public Character getAutorizar() {
		return this.autorizar;
	}
	
	public void setAutorizar(Character autorizar) {
		this.autorizar = autorizar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEREGISTRO", length = 7)
	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMihRol")
	public Set<TMihUsuario> getTMihUsuarios() {
		return this.TMihUsuarios;
	}

	public void setTMihUsuarios(Set<TMihUsuario> TMihUsuarios) {
		this.TMihUsuarios = TMihUsuarios;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombre();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
