package com.sophos.semih.model;

// Generated 27/08/2013 04:00:38 PM by Hibernate Tools 4.0.0

import java.util.Date;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihEntidadId generated by hbm2java
 */
public class TMihEntidadId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5199793644632241177L;
	private Integer codigo;
	private String nombre;
	private Date fecreacion;
	private String usrcreador;
	private Integer codaplicacion;
	private Integer tvigencia;
	private String depurar;
	private String usrsolcreacion;
	private String descripcion;
	private static final Log log = LogFactory.getLog(TMihEntidadId.class);

	public TMihEntidadId() {
	}

	public TMihEntidadId(Integer codigo, String nombre, Date fecreacion,
			String usrcreador, Integer codaplicacion, Integer tvigencia,
			String depurar, String usrsolcreacion, String descripcion) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.fecreacion = fecreacion;
		this.usrcreador = usrcreador;
		this.codaplicacion = codaplicacion;
		this.tvigencia = tvigencia;
		this.depurar = depurar;
		this.usrsolcreacion = usrsolcreacion;
		this.descripcion = descripcion;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFecreacion() {
		return this.fecreacion;
	}

	public void setFecreacion(Date fecreacion) {
		this.fecreacion = fecreacion;
	}

	public String getUsrcreador() {
		return this.usrcreador;
	}

	public void setUsrcreador(String usrcreador) {
		this.usrcreador = usrcreador;
	}

	public Integer getCodaplicacion() {
		return this.codaplicacion;
	}

	public void setCodaplicacion(Integer codaplicacion) {
		this.codaplicacion = codaplicacion;
	}

	public Integer getTvigencia() {
		return this.tvigencia;
	}

	public void setTvigencia(Integer tvigencia) {
		this.tvigencia = tvigencia;
	}

	public String getDepurar() {
		return this.depurar;
	}

	public void setDepurar(String depurar) {
		this.depurar = depurar;
	}

	public String getUsrsolcreacion() {
		return this.usrsolcreacion;
	}

	public void setUsrsolcreacion(String usrsolcreacion) {
		this.usrsolcreacion = usrsolcreacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMihEntidadId))
			return false;
		TMihEntidadId castOther = (TMihEntidadId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this
				.getCodigo() != null && castOther.getCodigo() != null && this
				.getCodigo().equals(castOther.getCodigo())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getFecreacion() == castOther.getFecreacion()) || (this
						.getFecreacion() != null
						&& castOther.getFecreacion() != null && this
						.getFecreacion().equals(castOther.getFecreacion())))
				&& ((this.getUsrcreador() == castOther.getUsrcreador()) || (this
						.getUsrcreador() != null
						&& castOther.getUsrcreador() != null && this
						.getUsrcreador().equals(castOther.getUsrcreador())))
				&& ((this.getCodaplicacion() == castOther.getCodaplicacion()) || (this
						.getCodaplicacion() != null
						&& castOther.getCodaplicacion() != null && this
						.getCodaplicacion()
						.equals(castOther.getCodaplicacion())))
				&& ((this.getTvigencia() == castOther.getTvigencia()) || (this
						.getTvigencia() != null
						&& castOther.getTvigencia() != null && this
						.getTvigencia().equals(castOther.getTvigencia())))
				&& ((this.getDepurar() == castOther.getDepurar()) || (this
						.getDepurar() != null && castOther.getDepurar() != null && this
						.getDepurar().equals(castOther.getDepurar())))
				&& ((this.getUsrsolcreacion() == castOther.getUsrsolcreacion()) || (this
						.getUsrsolcreacion() != null
						&& castOther.getUsrsolcreacion() != null && this
						.getUsrsolcreacion().equals(
								castOther.getUsrsolcreacion())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37
				* result
				+ (getFecreacion() == null ? 0 : this.getFecreacion()
						.hashCode());
		result = 37
				* result
				+ (getUsrcreador() == null ? 0 : this.getUsrcreador()
						.hashCode());
		result = 37
				* result
				+ (getCodaplicacion() == null ? 0 : this.getCodaplicacion()
						.hashCode());
		result = 37 * result
				+ (getTvigencia() == null ? 0 : this.getTvigencia().hashCode());
		result = 37 * result
				+ (getDepurar() == null ? 0 : this.getDepurar().hashCode());
		result = 37
				* result
				+ (getUsrsolcreacion() == null ? 0 : this.getUsrsolcreacion()
						.hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		return result;
	}

	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombre();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
