package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeId generated by hbm2java
 */
@Embeddable
public class EmployeeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1690854786251327283L;
	private Integer numero;
	private String nombre;

	public EmployeeId() {
	}

	public EmployeeId(Integer numero, String nombre) {
		this.numero = numero;
		this.nombre = nombre;
	}

	@Column(name = "NUMERO", precision = 8, scale = 0)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "NOMBRE", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeId))
			return false;
		EmployeeId castOther = (EmployeeId) other;

		return ((this.getNumero() == castOther.getNumero()) || (this
				.getNumero() != null && castOther.getNumero() != null && this
				.getNumero().equals(castOther.getNumero())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNumero() == null ? 0 : this.getNumero().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
