package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpXmlId generated by hbm2java
 */
@Embeddable
public class EmpXmlId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 102917367946257291L;
	private BigDecimal id;
	private String empname;
	private BigDecimal empsal;
	private Date empjoindate;

	public EmpXmlId() {
	}

	public EmpXmlId(BigDecimal id, String empname, BigDecimal empsal,
			Date empjoindate) {
		this.id = id;
		this.empname = empname;
		this.empsal = empsal;
		this.empjoindate = empjoindate;
	}

	@Column(name = "ID", precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "EMPNAME", length = 40)
	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	@Column(name = "EMPSAL", precision = 22, scale = 0)
	public BigDecimal getEmpsal() {
		return this.empsal;
	}

	public void setEmpsal(BigDecimal empsal) {
		this.empsal = empsal;
	}

	@Column(name = "EMPJOINDATE", length = 7)
	public Date getEmpjoindate() {
		return this.empjoindate;
	}

	public void setEmpjoindate(Date empjoindate) {
		this.empjoindate = empjoindate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpXmlId))
			return false;
		EmpXmlId castOther = (EmpXmlId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getEmpname() == castOther.getEmpname()) || (this
						.getEmpname() != null && castOther.getEmpname() != null && this
						.getEmpname().equals(castOther.getEmpname())))
				&& ((this.getEmpsal() == castOther.getEmpsal()) || (this
						.getEmpsal() != null && castOther.getEmpsal() != null && this
						.getEmpsal().equals(castOther.getEmpsal())))
				&& ((this.getEmpjoindate() == castOther.getEmpjoindate()) || (this
						.getEmpjoindate() != null
						&& castOther.getEmpjoindate() != null && this
						.getEmpjoindate().equals(castOther.getEmpjoindate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getEmpname() == null ? 0 : this.getEmpname().hashCode());
		result = 37 * result
				+ (getEmpsal() == null ? 0 : this.getEmpsal().hashCode());
		result = 37
				* result
				+ (getEmpjoindate() == null ? 0 : this.getEmpjoindate()
						.hashCode());
		return result;
	}

}
