package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihEntidad generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_ENTIDAD")
public class TMihEntidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2736765461092010946L;
	private int codigo;
	private TMihAplicacion TMihAplicacion;
	private String nombre;
	private Date fecreacion;
	private String usrcreador;
	private Integer tvigencia;
	private String depurar;
	private String vacia;
	private String campoFecha;
	private String usrsolcreacion;
	private String descripcion;
	private String campoLlave;
	private List<Campo> campos;
	private static final Log log = LogFactory.getLog(TMihEntidad.class);

	public TMihEntidad() {
	}

	public TMihEntidad(int codigo) {
		this.codigo = codigo;
	}

	public TMihEntidad(int codigo, TMihAplicacion TMihAplicacion,
			String nombre, Date fecreacion, String usrcreador,
			Integer tvigencia, String depurar, String vacia, String campoFecha,
			String usrsolcreacion, String descripcion, String campoLlave) {
		this.codigo = codigo;
		this.TMihAplicacion = TMihAplicacion;
		this.nombre = nombre;
		this.fecreacion = fecreacion;
		this.usrcreador = usrcreador;
		this.tvigencia = tvigencia;
		this.depurar = depurar;
		this.vacia = vacia;
		this.campoFecha = campoFecha;
		this.usrsolcreacion = usrsolcreacion;
		this.descripcion = descripcion;
		this.campoLlave = campoLlave;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_ent_id")
	@SequenceGenerator(name="seq_ent_id", sequenceName="SEQ_MIH_ENTIDAD",schema="SEMIH",allocationSize=5)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODAPLICACION")
	public TMihAplicacion getTMihAplicacion() {
		return this.TMihAplicacion;
	}

	public void setTMihAplicacion(TMihAplicacion TMihAplicacion) {
		this.TMihAplicacion = TMihAplicacion;
	}

	@Column(name = "NOMBRE", length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECREACION", length = 7)
	public Date getFecreacion() {
		return this.fecreacion;
	}

	public void setFecreacion(Date fecreacion) {
		this.fecreacion = fecreacion;
	}

	@Column(name = "USRCREADOR", length = 120)
	public String getUsrcreador() {
		return this.usrcreador;
	}

	public void setUsrcreador(String usrcreador) {
		this.usrcreador = usrcreador;
	}

	@Column(name = "TVIGENCIA", precision = 8, scale = 0)
	public Integer getTvigencia() {
		return this.tvigencia;
	}

	public void setTvigencia(Integer tvigencia) {
		this.tvigencia = tvigencia;
	}

	@Column(name = "DEPURAR", length = 4)
	public String getDepurar() {
		return this.depurar;
	}

	public void setDepurar(String depurar) {
		this.depurar = depurar;
	}

	@Column(name = "VACIA", length = 4)
	public String getVacia() {
		return this.vacia;
	}

	public void setVacia(String vacia) {
		this.vacia = vacia;
	}

	@Column(name = "CAMPOFECHA", length = 120)
	public String getCampoFecha() {
		return this.campoFecha;
	}

	public void setCampoFecha(String campoFecha) {
		this.campoFecha = campoFecha;
	}

	@Column(name = "USRSOLCREACION", length = 120)
	public String getUsrsolcreacion() {
		return this.usrsolcreacion;
	}

	public void setUsrsolcreacion(String usrsolcreacion) {
		this.usrsolcreacion = usrsolcreacion;
	}

	@Column(name = "DESCRIPCION", length = 1600)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CAMPOLLAVE", length = 30)
	public String getCampoLlave() {
		return this.campoLlave;
	}

	public void setCampoLlave(String campoLlave) {
		this.campoLlave = campoLlave;
	}

	@Transient
	public List<Campo> getCampos() {
		return campos;
	}

	public void setCampos(List<Campo> campos) {
		this.campos = campos;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombre();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}

}
