package com.sophos.semih.model;

// Generated 9/10/2013 03:53:50 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihSesion generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_SESION")
public class TMihSesion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5481618121547114832L;
	private String idUsuario;
	private String nombreUsuario;
	private String idSesion;
	private Character estado;
	private Timestamp fechaLogin;
	private static final Log log = LogFactory.getLog(TMihSesion.class);
	
	public TMihSesion() {
	}

	public TMihSesion(String idUsuario, String nombreUsuario, String idSesion, Character estado) {
		this.idUsuario = idUsuario;
		this.nombreUsuario = nombreUsuario;
		this.idSesion = idSesion;
		this.estado = estado;
	}

	public TMihSesion(String idUsuario, String nombreUsuario, String idSesion, Character estado,
			Timestamp fechaLogin) {
		this.idUsuario = idUsuario;
		this.nombreUsuario= nombreUsuario;
		this.idSesion = idSesion;
		this.estado = estado;
		this.fechaLogin = fechaLogin;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombreUsuario() {
		return nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(String idSesion) {
		this.idSesion = idSesion;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Timestamp getFechaLogin() {
		return this.fechaLogin;
	}

	public void setFechaLogin(Timestamp fechaLogin) {
		this.fechaLogin = fechaLogin;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombreUsuario();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}

	
}
