package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihEntxusrId generated by hbm2java
 */
@Embeddable
public class TMihEntxusrId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5019650154595234249L;
	private int codusuario;
	private int codentidad;
	private static final Log log = LogFactory.getLog(TMihEntxusrId.class);

	public TMihEntxusrId() {
	}

	public TMihEntxusrId(int codusuario, int codentidad) {
		this.codusuario = codusuario;
		this.codentidad = codentidad;
	}

	@Column(name = "CODUSUARIO", nullable = false, precision = 8, scale = 0)
	public int getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(int codusuario) {
		this.codusuario = codusuario;
	}

	@Column(name = "CODENTIDAD", nullable = false, precision = 8, scale = 0)
	public int getCodentidad() {
		return this.codentidad;
	}

	public void setCodentidad(int codentidad) {
		this.codentidad = codentidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMihEntxusrId))
			return false;
		TMihEntxusrId castOther = (TMihEntxusrId) other;

		return (this.getCodusuario() == castOther.getCodusuario())
				&& (this.getCodentidad() == castOther.getCodentidad());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodusuario();
		result = 37 * result + this.getCodentidad();
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			String codusuario = Integer.toString(getCodusuario());
			return codusuario;
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
	
}
