package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihAplicacion generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_APLICACION", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NOMBRE", "CODLINEANEGOCIO" }))
public class TMihAplicacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1420095550237796279L;
	private int codigo;
	private TMihLineanegocio TMihLineanegocio;
	private String nombre;
	private String descripcion;
	private Character estado;
	private Date feregistro;
	private Set<TMihEntidad> TMihEntidades = new HashSet<TMihEntidad>(0);
	private static final Log log = LogFactory.getLog(TMihAplicacion.class);

	public TMihAplicacion() {
	}

	public TMihAplicacion(int codigo) {
		this.codigo = codigo;
	}

	public TMihAplicacion(int codigo, TMihLineanegocio TMihLineanegocio,
			String nombre, String descripcion, Character estado,
			Date feregistro, Set<TMihEntidad> TMihEntidades) {
		this.codigo = codigo;
		this.TMihLineanegocio = TMihLineanegocio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.feregistro = feregistro;
		this.TMihEntidades = TMihEntidades;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_apl_id")
	@SequenceGenerator(name="seq_apl_id", sequenceName="SEQ_MIH_APLICACION",schema="SEMIH",allocationSize=5)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODLINEANEGOCIO")
	public TMihLineanegocio getTMihLineanegocio() {
		return this.TMihLineanegocio;
	}

	public void setTMihLineanegocio(TMihLineanegocio TMihLineanegocio) {
		this.TMihLineanegocio = TMihLineanegocio;
	}

	@Column(name = "NOMBRE", length = 160)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 1600)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEREGISTRO", length = 7)
	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMihAplicacion")
	public Set<TMihEntidad> getTMihEntidades() {
		return this.TMihEntidades;
	}

	public void setTMihEntidades(Set<TMihEntidad> TMihEntidades) {
		this.TMihEntidades = TMihEntidades;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return getNombre();
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}

}
