package com.sophos.semih.model;

// Generated Dec 11, 2013 4:35:18 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 * TMihConsulta generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_CONSULTA")
public class TMihConsulta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1772365897371158603L;
	private int codigo;
	private TMihUsuario TMihUsuario;
	private String descripcion;
	private Date fechacreacion;
	private static final Log log = LogFactory.getLog(TMihConsulta.class);

	public TMihConsulta() {
	}

	public TMihConsulta(int codigo) {
		this.codigo = codigo;
	}

	public TMihConsulta(int codigo, TMihUsuario codusuario, String descripcion,
			Date fechacreacion) {
		this.codigo = codigo;
		this.TMihUsuario = codusuario;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
	}
	
	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getCodigo() {
		return this.codigo;
	}
	

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODUSUARIO")
	public TMihUsuario getTMihUsuario() {
		return this.TMihUsuario;
	}

	public void setTMihUsuario(TMihUsuario TMihUsuario) {
		this.TMihUsuario = TMihUsuario;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return String.valueOf(getCodigo());
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}

}
