package com.sophos.semih.model;

// Generated 9/10/2013 04:13:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMihTipocatalogo generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_TIPOCATALOGO")
public class TMihTipocatalogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2708289461336028841L;
	private short codmaestro;
	private String tipomaestro;
	private Date feregistro;
	private Set<TMihCatalogo> TMihCatalogos = new HashSet<TMihCatalogo>(0);

	public TMihTipocatalogo() {
	}

	public TMihTipocatalogo(short codmaestro) {
		this.codmaestro = codmaestro;
	}

	public TMihTipocatalogo(short codmaestro, String tipomaestro,
			Date feregistro, Set<TMihCatalogo> TMihCatalogos) {
		this.codmaestro = codmaestro;
		this.tipomaestro = tipomaestro;
		this.feregistro = feregistro;
		this.TMihCatalogos = TMihCatalogos;
	}

	@Id
	@Column(name = "CODMAESTRO", unique = true, nullable = false, precision = 4, scale = 0)
	public short getCodmaestro() {
		return this.codmaestro;
	}

	public void setCodmaestro(short codmaestro) {
		this.codmaestro = codmaestro;
	}

	@Column(name = "TIPOMAESTRO", length = 120)
	public String getTipomaestro() {
		return this.tipomaestro;
	}

	public void setTipomaestro(String tipomaestro) {
		this.tipomaestro = tipomaestro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEREGISTRO", length = 7)
	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMihTipocatalogo")
	public Set<TMihCatalogo> getTMihCatalogos() {
		return this.TMihCatalogos;
	}

	public void setTMihCatalogos(Set<TMihCatalogo> TMihCatalogos) {
		this.TMihCatalogos = TMihCatalogos;
	}
	
	// This must return true for another TMihTipocatalogo object with same codmaestro.
    public boolean equals(Object other) {
        return other instanceof TMihTipocatalogo && (codmaestro != 0) ? codmaestro==(((TMihTipocatalogo) other).codmaestro) : (other == this);
    }

    // This must return the same hashcode for every codmaestro object with the same key.
    public int hashCode() {
        return codmaestro != 0 ? this.getClass().hashCode() + String.valueOf(codmaestro).hashCode() : super.hashCode();
    }
    
    public String toString() {
        return codmaestro+"";
    }
}
