package com.sophos.semih.model;

// Generated Dec 11, 2013 4:35:18 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihConstbl generated by hbm2java
 */
@Entity
@Table(name = "T_MIH_CONSTBL")
public class TMihConstbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1164886951925386887L;
	private TMihConstblId id;
	private TMihEntidad TMihEntidad;
	private TMihConsulta TMihConsulta;
	private static final Log log = LogFactory.getLog(TMihConstbl.class);

	public TMihConstbl() {
	}

	public TMihConstbl(TMihConstblId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codentidad", column = @Column(name = "CODENTIDAD", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "codconsulta", column = @Column(name = "CODCONSULTA", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "sec", column = @Column(name = "SEC", nullable = false, precision = 2, scale = 0)) })
	
	public TMihConstblId getId() {
		return this.id;
	}

	public void setId(TMihConstblId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODCONSULTA", nullable = false, insertable = false, updatable = false)
	public TMihConsulta getTMihConsulta() {
		return this.TMihConsulta;
	}
	
	public void setTMihConsulta(TMihConsulta TMihConsulta) {
		this.TMihConsulta = TMihConsulta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODENTIDAD", nullable = false, insertable = false, updatable = false)
	public TMihEntidad getTMihEntidad() {
		return this.TMihEntidad;
	}

	public void setTMihEntidad(TMihEntidad TMihEntidad) {
		this.TMihEntidad = TMihEntidad;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return String.valueOf(getId().getCodconsulta());
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}
}
