package com.sophos.semih.model;

// Generated Dec 11, 2013 4:35:18 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * TMihConsfldId generated by hbm2java
 */
@Embeddable
public class TMihConsfldId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4926420321876453175L;
	private int codentidad;
	private int codconsulta;
	private String campo;
	private short sec;
	private short sectabla;
	private static final Log log = LogFactory.getLog(TMihConsfldId.class);

	public TMihConsfldId() {
	}

	public TMihConsfldId(int codentidad, int codconsulta, String campo,
			short sec, short sectabla) {
		this.codentidad = codentidad;
		this.codconsulta = codconsulta;
		this.campo = campo;
		this.sec = sec;
		this.sectabla = sectabla;
	}

	@Column(name = "CODENTIDAD", nullable = false, precision = 8, scale = 0)
	public int getCodentidad() {
		return this.codentidad;
	}

	public void setCodentidad(int codentidad) {
		this.codentidad = codentidad;
	}

	@Column(name = "CODCONSULTA", nullable = false, precision = 8, scale = 0)
	public int getCodconsulta() {
		return this.codconsulta;
	}

	public void setCodconsulta(int codconsulta) {
		this.codconsulta = codconsulta;
	}

	@Column(name = "CAMPO", nullable = false, length = 128)
	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	@Column(name = "SEC", nullable = false, precision = 4, scale = 0)
	public short getSec() {
		return this.sec;
	}

	public void setSec(short sec) {
		this.sec = sec;
	}

	@Column(name = "SECTABLA", nullable = false, precision = 4, scale = 0)
	public short getSectabla() {
		return this.sectabla;
	}

	public void setSectabla(short sectabla) {
		this.sectabla = sectabla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMihConsfldId))
			return false;
		TMihConsfldId castOther = (TMihConsfldId) other;

		return (this.getCodentidad() == castOther.getCodentidad())
				&& (this.getCodconsulta() == castOther.getCodconsulta())
				&& ((this.getCampo() == castOther.getCampo()) || (this
						.getCampo() != null && castOther.getCampo() != null && this
						.getCampo().equals(castOther.getCampo())))
				&& (this.getSec() == castOther.getSec())
				&& (this.getSectabla() == castOther.getSectabla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodentidad();
		result = 37 * result + this.getCodconsulta();
		result = 37 * result
				+ (getCampo() == null ? 0 : this.getCampo().hashCode());
		result = 37 * result + this.getSec();
		result = 37 * result + this.getSectabla();
		return result;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		try {
			return String.valueOf(getCodconsulta());
		} catch (Exception e) {
			log.error("Error en toString()", e);
		}
		return null;
	}

}
